### ISSUE TITLE
Add supplementary survey metadata and associated rules

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/ala-tern#15]
Add new fields to the survey metadata ("survey info" tab).

Note attributes for inclusion as supplementary survey metadata coloured red and marked by "Y" in column D of the spreadsheet https://docs.google.com/spreadsheets/d/1iR2Re3c0EVRcK2FXXm1o51K0aOtw3Q9k_aUCFJ4k0BQ/edit#gid=19280177.
Also take note of any relevant implementation comments in column B.

**Comment by nickdos** [comment]
@pbrenton Is this the file to be updated: https://github.com/AtlasOfLivingAustralia/ecodata/blob/master/models/biologicalSurveyInformation/dataModel.json ?

**Comment by patkyn** [comment]
After discussion with @pbrenton, survey records need to display DOI information. 
A button/link need to be displayed if the Survey record has got Site and Method information. 
When user click on the button, the following fields will need to be displayed:
1) Date of Submission
2) Submitter
3) Dataset Version
4) DOI reference (link to AEKOS)

**Comment by pbrenton** [comment]
Not quite Patricia.
This requirement should actually be documented in issue #17 instead of this one. The 4 fields indicated should be displayed as a table in an expandable drop-down section on the survey list page ("Surveys" tab) below existing survey information if a survey has been submitted to SHaRED. The event to expand this section would be another button below the "Show records" button titled "View in AEKOS". This button should only be displayed with a survey if the survey metadata contains a method and the survey has at least one record with a site.

Within the expandable section there also needs to be a button titled "Submit current version to AEKOS" which will manually trigger the submission workflow.

**Comment by patkyn** [comment]
Got it...wasn't aware of issue #17.

**Comment by patkyn** [comment]
Review link
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-138

**Comment by pbrenton** [comment]
some changes requested in issue #18
